// Get all the elements with the class 'css-dza7r7' (the containers holding download buttons. This seems to be autogenerated so I'll have to refind it next year.)
const listOfDownloads = document.getElementsByClassName('css-dza7r7');
for (let i = 0; i < listOfDownloads.length; i++) {
    const downloadButton = listOfDownloads[i].querySelector('.css-hmhqzt'); // This class is the button class itself. It's autogenerated so I'll have to refind it next year.

    // If the download button is found, click it
    if (downloadButton) {
        downloadButton.click();
        console.log(`Clicked download button ${i + 1}`);
    } else {
        console.log(`Download button not found for item ${i + 1}`);
    }
}

/*
NOTE!!! 
 I'm annoyed that shortbox comics fair doesn't have a download all button for comic hoarders like me. 
 This garbo code is quick and dirty and doesn't work for whatever reason in firefox. 
 In chrome and edge you will need to allow popups on your order's downloads page for this to download everything. 
 This note also serves as your epilepsy warning. 
 I highly suggest your open up your order's downloads page in new window before running this.
*/
